### PR TITLE
Bug resolve : module not found

### PR DESCRIPTION
**Pull request by harshilparmar**
I was getting an error while setup up a development environment.

`Module not found: Can't resolve './react-day-picker/dist/style.css' in 'D:\opensource\react-day-picker\website\src\components\Frame'`

In this error, I just replaced path of style.css based on `htmlContent` file path and its working fine. I hope this is valid solution. I have done this based on my knowledge, please correct me If I am wrong.

### CODE REVIEW

**Review by jalispran — APPROVED** [review]
I was facing the same error. This change solved it.

**Comment by harshilparmar** [comment]
@jalispran Thanks!!!

**Comment by harshilparmar** [comment]
@gpbl Can you please check this changes?

**Comment by jalispran** [comment]
@harshilparmar please refer #1061

**Comment by gpbl** [comment]
Yeah sorry for that, running yarn build is required to copy that file :(

**Pull request closed without merging**
