### PR TITLE
Add focus() method for focusing DayPicker wrapper

### PR DESCRIPTION
**Pull request by strax**
Adds a `focus` method on the `DayPicker` instance which moves user agent focus to the wrapper element (provided it has `tabIndex` not set to undefined). This is useful for accessibility purposes when the date picker is shown based on user interaction like clicking a button.

### CODE REVIEW

**Comment by Kaandriambelo** [comment]
I would like to navigate from the input field to the calendar through keyboards only. I think i need to use this focus function to achieve that. Do you have a sandbox example about how to use this focus function ?

**Comment by strax** [comment]
@gpbl Is there anything we could do to make this PR move forward?

**Comment by ktschanz** [comment]
> I would like to navigate from the input field to the calendar through keyboards only. I think i need to use this focus function to achieve that. Do you have a sandbox example about how to use this focus function ?

I need this too. Any update?

**Comment by wongcode** [comment]
+1 to getting this into a release!

**Comment by davidspiess** [comment]
@gpbl any change to merge this?

**Comment by ntanguay** [comment]
Would also like this merged in!

**Comment by mackenzie-gray** [comment]
merge soon? 😄

**Comment by gpbl** [comment]
I'll try to cut the release in the next days, please be patient (you are because this is 1 year old :)) !

The new release will have a different approach to input:

https://rdp-v8.netlify.com/docs/input

feedback appreciated at #944 thanks.

**Pull request merged**
