### PR TITLE
Combine UMD configs with rollup multiconfig and add size snapshot

### PR DESCRIPTION
**Pull request by TrySound**
This will reduce cost of running node and loading rollup twice.

### CODE REVIEW

**Comment by gpbl** [comment]
Some more explanation please? :)

**Comment by TrySound** [comment]
I have a plan to distribute also cjs and esm bundles instead of many files. This will also reduce the cost of bundling vendors.

**Comment by TrySound** [comment]
Added [rollup-plugin-size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot). I created this plugin for improving bundles of frontend projects.

**Comment by TrySound** [comment]
Ant thoughts?

**Comment by gpbl** [comment]
@TrySound thanks this work has been landed into #944. Would love a review there, if you still have time :)

**Pull request closed without merging**
