### PR TITLE
Add isFutureDay DateUtils function

### PR DESCRIPTION
**Pull request by McFreely**
While using the picker, I felt the need to exclude days in the future, instead of days in the past. There is nothing ground-breaking here.

I've also added tests and documentation.

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks! Would you mind to fix the lint issues so the Travis build can pass?
https://travis-ci.org/gpbl/react-day-picker/builds/157622516 🙏🏽

**Comment by McFreely** [comment]
Yep, it's done.
But i'm at a loss about the coverage decreasing...

**Comment by gpbl** [comment]
Ah I have no idea eithe 😄 I'll check it. Thanks again

**Comment by gpbl** [comment]
I'll cut a release within the next weeks, please have some patience ...

**Comment by McFreely** [comment]
Cheers, thanks for your reactivity! Have a good day!

**Pull request merged**
