### PR TITLE
Add flow types definition

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/gpbl/react-day-picker/issues/483

### CODE REVIEW

**Comment by TrySound** [comment]
@gpbl Is it good for you?

**Comment by adidahiya** [comment]
sigh. this makes me sad because the syntax is almost identical to the typescript definitions that already exist in this project and now we're stuck maintaining both. not sure what can be done about it though...

**Comment by TrySound** [comment]
Syntax is similar but react libs are quite different.

**Comment by adidahiya** [comment]
> react libs are quite different

what do you mean? do you mean that react's flow typings are quite different from `@types/react`? how so?

**Comment by TrySound** [comment]
Lot of stuff. In flow Synthetic[Mouse|Keyboard|Input...]Event events are global and doesn't have target generics. And another React stuff has different names. Also typescript namespaces with synthetic exports are incompatible with flow and will be broken with native modules some day.

**Comment by TrySound** [comment]
@gpbl do you have a plan to publish this?

**Comment by stunaz** [comment]
@gpbl what is holding you from publishing this?

**Comment by TrySound** [comment]
We need to upgrade them to flow55 and rebase pr. I don't have a time right now.

**Comment by gpbl** [comment]
We moved to typescript: https://github.com/gpbl/react-day-picker/pull/944 no plans to add flow anymore... thanks!

**Pull request closed without merging**
