### PR TITLE
Refactor typescript definitions, expose DayPickerInput

### PR DESCRIPTION
**Pull request by adidahiya**
This PR:

- Refactors typescript definitions into multiple files in the `types/` folder
- Exposes `DayPickerInput` types in a new file called `DayPickerInput.d.ts`
- Supersedes #485 

@gpbl @lpcarignan

### CODE REVIEW

**Comment by lpcarignan** [comment]
I'm sorry to report that this does not work in my test sample project [DayPickerInputType](https://github.com/lpcarignan/DayPickerInputTypescript).

When I put the files of this PR in `node_modules/react-day-picker/types`, and I run `tsc`. I get the following errors:

```
main.tsx(8,28): error TS2497: Module '"DayPickerInputTypescript/node_modules/react-day-picker/types/index"' resolves to a non-module entity and cannot be imported using this construct.
main.tsx(9,33): error TS7016: Could not find a declaration file for module 'react-day-picker/DayPickerInput'. 'DayPickerInputTypescript/node_modules/react-day-picker/DayPickerInput.js' implicitly has an 'any' type.
```

I like your idea of splitting the type definitions into separate files.

I really appreciate your efforts @adidahiya at helping me with this. Would it be too much to ask you to test your pull request (or other solutions) in my sample Typescript project? After doing a `npm install` on this sample project, you can copy your files in `node_modules/react-day-picker/types` and run `tsc`.

While I understand `export.module = DayPicker.default || DayPicker;` should not change, I am of the opinion that naming it will make the Typescript compiler happy.

Finally, as my experience with Typescript/Javascript is limited, I am more than open to any other solution as long as it works in a Typescript project.

**Comment by lpcarignan** [comment]
@adidahiya and @gpbl, I was wondering if there was still interest in regards to my last comment.

I can understand we all have other priorities with work so not a problem if my request is on the back burner. I just wanted to let you know that I'm still willing to collaborate and make react-day-picker easy to use in Typescript.

**Comment by KyleGobel** [comment]
Sorry, I'm just trying to catch up here, trying to use this in Typescript and yeah..it doesn't work at all.  Do we know what the 'base' issue is? 

Even after deleting the typings file and just trying to import it like the demos show regular JS mode I still get errors 
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```

Some non standard way of exporting or something going on?

**Comment by lpcarignan** [comment]
@KyleGobel 
Thx for letting me know it works in your project. There was a 6.1.1 release a few days ago. 

Do you use the controls in something similar to this?

```
render(): JSX.Element {
        return (
            <div>
                <DayPicker
                    selectedDays={this.state.selectedDays}
                    onDayClick={this.handleDayClick.bind(this)}
                />
                <DayPickerInput value="MM/DD/YYYY" format="MM/DD/YYYY" />
                <p>
                    {this.state.selectedDays
                        ? this.state.selectedDays.toLocaleDateString()
                        : 'Please select a day 👻'}
                </p>
            </div>
        );
    }

```

**Comment by gpbl** [comment]
Hi everyone, so is this OK to merge? Is there a way to test it? I’m fine to merge it but I’d like to be sure it works as expected.  I’d be happy to include this change in the upcoming release.
Sadly I’ve not the time to jump into TypeScript right now to setup. Thanks for your patience!

**Comment by lpcarignan** [comment]
@gpbl 
I never had any feedback from my Aug 29 comment so I dropped the ball.

Based on @KyleGobel comment today, I'll find some time to test the latest version (6.1.1) of react-day-picker in my sample project [DayPickerInputType](https://github.com/lpcarignan/DayPickerInputTypescript).

I would be more than happy @gpbl if you could also test the modifications in this pull request in my sample project [DayPickerInputType](https://github.com/lpcarignan/DayPickerInputTypescript). I gave feedback from your team recommandations at the end of August in this pull request on this sample project but never got any feedback in return :-(

**Comment by gpbl** [comment]
@lpcarignan thanks again for your effort, but I don't understand which action should I take from your feedback. I'll merge this as I need it for https://github.com/gpbl/react-day-picker/pull/501. If something will break I hope someone will fix it in a PR :)

**Comment by gpbl** [comment]
Good news! Landed on v6.2 – thanks @adidahiya and @lpcarignan for the invaluable help 💟

**Pull request merged**
