### PR TITLE
Replace moment specifier with format/parse functions

### PR DESCRIPTION
**Pull request by TrySound**
This PR will remove moment dependency in favour of parse and format helpers which can be handled with library chosen in a team.

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks for this PR! 

I was thinking to provide a default format, e.g. `format` could return the day as `YYYY-MM-DD`, and `parse` would convert it to a `Date` object. `String(new Date())` is a bit too generic as it returns also the time.

I was reasoning about writing a small utility that could recognize `D`, `DD`, `M, `MM`, `YY` and `YYYY` as format strings, so that `format` would accept also strings like `DD-MM-YY` and `parse` would convert them accordingly. The idea is to cover the most common cases without writing too much code.

**Comment by gpbl** [comment]
@TrySound also I believe `parse` and `format` should receive the `locale` as second argument, which may come from the `dayPickerProps`.

```jsx
const parse = (string, locale) => { return 'parsedDate' };
const format = (date, locale) => { return 'string' };

<DayPickerInput 
  dayPickerProps={{ locale: 'ru' }} 
  format={format} 
  parse={parse}
/>
```

This would help developers to implement their own i18n.

**Comment by TrySound** [comment]
Maybe better to pass date objects directly and use internal format and parser for simple specifer as defaults.  So you don't need to expose these defaults to let users understand date.

**Comment by gpbl** [comment]
> Maybe better to pass date objects directly and use internal format and parser for simple specifer as defaults. So you don't need to expose these defaults to let users understand date.

Not sure I follow – what do you mean?

**Comment by TrySound** [comment]
`<DateInput value={new Date(1992, 12, 20)} onChange={d => console.log(d.toISOString())} />`
This will allow to work with date directly without parsing received date

**Comment by gpbl** [comment]
OK, this is another change we can consider, and it makes sense – as it is somewhat related to https://github.com/gpbl/react-day-picker/issues/508 ("Move input related props to `inputProps`").

Until now, the `value` prop means "value" as in input fields, i.e. is expected to be a string. Once we close #508, we can do this. However, I'd open another PR for this change – on the master branch where moment is still a required dependency – to be sure we update the tests just for that change.

**Comment by gpbl** [comment]
I also think we should open a `v7` branch and merge these PR there. 

There are still [some fixes to do](https://github.com/gpbl/react-day-picker/milestone/11) on v6 that I would like to publish before other breaking changes.

**Comment by PeterKottas** [comment]
Hi guys, where do we stand with this? Do we have a date in mind for v7? I rly think getting rid of this moment dep is high priority

**Comment by gpbl** [comment]
@PeterKottas me too :) The problem is that there's a pending minor release, I'm working on it right now. 

I'd like to release this minor version where you can _optionally opt out_ from moment. I.e., it defaults to moment, but if you specify `format` and `parse` attribute, it will not. I'm not sure if it is possible, however.

**Comment by PeterKottas** [comment]
Oh that sounds cool. You should definitely be able to do that. Just require the module, then check if it's define before you use it and fallback to some detetime format. I think you already have logic for that there. It would however need to remain a peer dependency which scares some people away. But it it's only for now, I'd go for it.

**Pull request merged**
