### PR TITLE
Remove bower

### PR DESCRIPTION
**Pull request by TrySound**
Close https://github.com/gpbl/react-day-picker/issues/633

### CODE REVIEW

**Comment by gpbl** [comment]
Why this? 🤔

**Comment by TrySound** [comment]
I thought you wanted to remove bower. So lib won't be necessary to commit. Loading umd can be solved with http://unpkg.com/

**Comment by gpbl** [comment]
So this is related to bower or to roll up? 

Sorry it’s a while I don’t change the config for a lib so i may miss something here. How do people access to the compiled js module and CSS?

**Comment by TrySound** [comment]
```js
import { DayPicker } from 'react-day-picker';
import 'react-day-picker/lib/styles.css'
```

**Comment by TrySound** [comment]
Compiled code and styled It will be published on npm. Bundlers will use them.

**Comment by gpbl** [comment]
Maybe i should check this PR once I’m pn my computer but isn’t this removing the lib folder? 🤨

**Comment by gpbl** [comment]
Oh so OK when building we still create `lib`! 👍🏽

**Comment by gpbl** [comment]
Could we please remove also bower.json?

**Comment by gpbl** [comment]
Thanks!!

**Comment by gpbl** [comment]
(@TrySound I'm merging the v8 related PRs to the `v8` branch.)

**Pull request merged**
