### PR TITLE
Make sure utilities are exported again

### PR DESCRIPTION
**Pull request by gpbl**
Ref #658 cc @TrySound

### CODE REVIEW

**Comment by TrySound** [comment]
Do you expect more patch/minor releases? We probably can get rid from all legacy entry points and default exports.

**Comment by gpbl** [comment]
Yeah better put order in the exports in v8 (rollup).

**Comment by TrySound** [comment]
@gpbl I mean can we start working on v8?

**Comment by gpbl** [comment]
I think this PR can go in a patch. But does it fix the UMD export?

**Comment by TrySound** [comment]
Okay. Let's merge this then.

**Pull request merged**
