### PR TITLE
Change interfaces to namespaces

### LINKED ISSUE #865: modules/react-day-picker/types has no export for 'DateUtils'
Error :react-day-picker/types"' has no exported member 'DateUtils'.

```tsx
import DayPicker, { DateUtils } from 'react-day-picker';

public handleDayClick(day: any) {
    const range = DateUtils.addDayToRange(day);
    this.setState(range);
}
```

Have checking node modules types/utils.d.ts

```tsx
export interface DateUtils {
  addDayToRange(day: Date, range: RangeModifier): RangeModifier;
  addMonths(d: Date, n: number): Date;
  clone(d: Date): Date;
  isDayAfter(day1: Date, day2: Date): boolean;
  isDayBefore(day1: Date, day2: Date): boolean;
  isDayBetween(day: Date, begin: Date, end: Date): boolean;
  isDayInRange(day: Date, range: RangeModifier): boolean;
  isFutureDay(day: Date): boolean;
  isPastDay(day: Date): boolean;
  isSameDay(day1: Date, day2: Date): boolean;
}
```

### LINKED ISSUE #887: 'DateUtils' only refers to a type, but is being used as a value here.
Hello guys, 

i thought i can reproduce error on sandbox, but it worked perfectly on it. Error i got is "'DateUtils' only refers to a type, but is being used as a value here." . Maybe someone has confronted similar error? 

I am using --Select days on mouse enter-- 100% coppied from examples.

Maybe have any solutions? Thx in advance :)

### PR DESCRIPTION
**Pull request by walston**
👋🏽 Thanks for opening a pull request!

Fixes an issue where TS complains:

> `DateUtils` only refers to a type but is being used as a value here `TS2693`

resolves #887 & resolves #865

### CODE REVIEW

**Comment by walston** [comment]
i'm trying to fix tests, but they seem to be unrelated to my changes... not sure how to go about this

**Comment by gpbl** [comment]
Thanks @walston – I'll check it out about the failing tests.

**Comment by DylanVann** [comment]
I'm not sure namespaces are the best approach: https://github.com/babel/babel/issues/8244#issuecomment-401616905

**Comment by Nibblesh** [comment]
I've thrown another potential solution up

**Comment by gpbl** [comment]
Fixed in #904

**Pull request closed without merging**
