### PR TITLE
Fix input field clear

### PR DESCRIPTION
**Pull request by ntlf**
`typedValue: undefined` could cause controlled/uncontrolled error since input's value calculation was changed in https://github.com/gpbl/react-day-picker/pull/816

If we set `typedValue: ''` then the input stays controlled, and we can clear the field correctly by setting empty string as value.

Closes https://github.com/gpbl/react-day-picker/issues/977 https://github.com/gpbl/react-day-picker/issues/955

### CODE REVIEW

**Comment by kimyu92** [comment]
@gpbl can you review this?

**Comment by EsdrasXavier** [comment]
@gpbl  Can you please review and accept it? I really need this for my current project and this will help a lot. Please review it!!

**Comment by andrewmmc** [comment]
May I know the review progress? Thank you!

**Comment by SCHUGRWS** [comment]
Please, @gpbl, can you or someone else review it? I really need it working to solve a issue in my project.

**Comment by Arcticroman** [comment]
Hi @gpbl , could you please review this pr? 
Thank you, have a nice day)

**Comment by rhahne** [comment]
Hey @gpbl, would be great if this PR gets merged soon, thanks!

**Comment by sousajunior** [comment]
@gpbl can you review this? please!

**Pull request merged**
