### PR TITLE
build: date-fns as regular dependency

### PR DESCRIPTION
**Pull request by benasher44**
## Description

See gpbl/react-day-picker#2240

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

Before submitting your pull request, please make sure the following is done:

- [x] I have read the [CONTRIBUTING](./CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have followed the coding guidelines in this project
- [ ] I have tested my changes on different browsers and screen sizes

## Linked Issues

gpbl/react-day-picker#2240

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks, but what about the [locale prop](https://daypicker.dev/next/using-daypicker/localization#set-a-different-locale), the [jalali calendar](https://daypicker.dev/next/using-daypicker/localization#jalali-calendar) and the [utc dates](https://daypicker.dev/next/using-daypicker/localization#utc-dates)? 


While we can add `date-fns-jalali` and `@date-fns/utc` to the dependencies, I'm not about the right approach for the locale prop.

I'm considering something like:


```diff
- import { es } from "date-fns/locale";
+ import { es } from "react-day-picker/locale";

<DayPicker locale={es} />; // Set the locale to Spanish
```

**Comment by gpbl** [comment]
... working on this.

**Comment by benasher44** [comment]
Thank you!

**Comment by gpbl** [comment]
You welcome! Thanks for the help.

**Pull request merged**
