### PR TITLE
Add support for adjusting the `initialMonth` to the start of a page.

### PR DESCRIPTION
**Pull request by zaygraveyard**
As discussed in [#196](https://github.com/gpbl/react-day-picker/issues/196#issuecomment-233597654).

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks! Going to cut the release in few hours.

**Comment by zaygraveyard** [comment]
Great, thank you!

**Comment by gpbl** [comment]
@zaygraveyard Sorry I can't make it for today! Let see tomorrow:)

**Comment by zaygraveyard** [comment]
It's ok, no worries 😃

**Pull request merged**
