### PR TITLE
Add support for publishing to bower

### PR DESCRIPTION
**Pull request by JKillian**
Here's a simple Bower build that'll expose a global `DayPicker` variable. Bower uses git tags to keep track of the current version, so you'll have to add a tag when you change the version in `package.json`.  (Here are the [bower docs](http://bower.io/docs/creating-packages/) for convenience.) Let me know if you have any questions!

### CODE REVIEW

**Comment by JKillian** [comment]
Related to #79

**Comment by gpbl** [comment]
Nice, thanks! But how does bower know we have a new bower-enabled package?

**Comment by gpbl** [comment]
I've made some changes with #85

**Comment by JKillian** [comment]
:+1: 

As far as bower, you just have to use [bower register](http://bower.io/docs/creating-packages/#register) once and add git tags to mark releases. (I'd assume you'd just do this whenever you update the version in package.json and get ready to push a new release to npm.)

**Comment by JKillian** [comment]
By the way, really like this component! It's the best React one of its kind I could find out there

**Comment by gpbl** [comment]
> By the way, really like this component! It's the best React one of its kind I could find out there

Thanks! Indeed I feel it deserves some more stars 😢

**Pull request merged**
