### PR TITLE
Add TypeScript declaration for utils.js

### PR DESCRIPTION
**Pull request by adam187**
Add missing declaration file for `utils.js` file.

```typescript

import { localeUtils, dateUtils, modifiersUtils } from 'react-day-picker/utils'

```

### CODE REVIEW

**Comment by DylanVann** [comment]
There doesn't need to be a declaration file for every source file, there just needs to be declarations for the public API

**Comment by adam187** [comment]
@DylanVann This file [utils.js](https://github.com/gpbl/react-day-picker/blob/master/utils.js) actually looks to me like public API.  

Currently, you can't use utils function like in docs in typescript because of type/export conflicts but looks like [this PR](https://github.com/gpbl/react-day-picker/pull/899/files) should solve it.

```typescript
import { DateUtils } from "react-day-picker";
```

`'DateUtils' only refers to a type, but is being used as a value here.ts`

**Comment by DylanVann** [comment]
Yeah I’m aware of the issue I’m just not sure this will do anything to help, also aware of that PR since I made it :)

**Comment by gpbl** [comment]
#899 has been merged 🎊

**Pull request closed without merging**
